name: zoombox_app_redux
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  http: ^0.12.0
  built_value: ^6.1.6
  built_collection: ^4.0.0
  built_value_generator: ^6.1.6
  code_builder: ^3.1.3
  build_runner: ^1.0.0
  analyzer: ^0.33.3
  shared_preferences: ^0.4.3


dependency_overrides:
  built_value : ^6.1.6
  built_collection: ^4.0.0


  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
 # flutter_test:
#    sdk: flutter

flutter:

  uses-material-design: true

